# Generated by Django 2.1.15 on 2021-04-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210425_1157'),
        ('reses', '0002_auto_20210411_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente'),
        ),
    ]
