# Generated by Django 2.1.15 on 2021-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('mercaderia', 'mercaderia'), ('carne', 'carne')], max_length=50, null=True),
        ),
    ]
