# Generated by Django 2.1.15 on 2021-04-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sm',
        ),
    ]
