# Generated by Django 2.1.15 on 2021-04-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
    ]
